db envs configured

diff --git a/.github/workflows/infra-deploy.yml b/.github/workflows/infra-deploy.yml
--- a/.github/workflows/infra-deploy.yml
+++ b/.github/workflows/infra-deploy.yml
@@ -46,6 +46,10 @@ jobs:
           terraform output -json > $GITHUB_WORKSPACE/ansible/inventory.json
           cat $GITHUB_WORKSPACE/ansible/inventory.json
         working-directory: terraform
+      - name: Set Environment Variables from Terraform Outputs
+       run: |
+        echo "DB_HOST=$(jq -r '.db_host.value' ansible/inventory.json)" >> $GITHUB_ENV
+        echo "DB_PASSWORD_SECRET_ARN=$(jq -r '.db_password_secret_arn.value' ansible/inventory.json)" >> $GITHUB_ENV
       - name: Upload Inventory JSON
         uses: actions/upload-artifact@v4
         with:
@@ -75,13 +79,15 @@ jobs:
           ssh-add ~/.ssh/trojan.pem
       - name: Retrieve DB Password from AWS Secrets Manager
         run: |
-          echo "DB_PASSWORD=$(aws secretsmanager get-secret-value --secret-id ${{ secrets.DB_PASSWORD_SECRET_ARN }} --query 'SecretString' --output text)" >> $GITHUB_ENV
-
-      - name: Run Ansible Playbook
-        run: |
-          cat inventory.json    
-          ansible-playbook -i inventory.json webserver.yml
-        working-directory: ansible
+          if [ -z "${{ env.DB_PASSWORD_SECRET_ARN }}" ]; then
+            echo "Error: DB_PASSWORD_SECRET_ARN is missing!" && exit 1
+          fi
+          echo "DB_PASSWORD=$(aws secretsmanager get-secret-value --secret-id ${{ env.DB_PASSWORD_SECRET_ARN }} --query 'SecretString' --output text)" >> $GITHUB_ENV
+            - name: Run Ansible Playbook
+              run: |
+                cat inventory.json    
+                ansible-playbook -i inventory.json webserver.yml
+              working-directory: ansible
       - name: Install MySQL Client
         run: |
           sudo apt update
@@ -89,6 +95,9 @@ jobs:
           pip3 install pymysql mysqlclient
       - name: Create Database
         run: |
+          if [ -z "${{ env.DB_HOST }}" ] || [ -z "${{ env.DB_PASSWORD }}" ]; then
+            echo "Error: Missing DB_HOST or DB_PASSWORD!" && exit 1
+          fi
           mysql -h "${{ env.DB_HOST }}" -u admin -p"${{ env.DB_PASSWORD }}" -e "CREATE DATABASE IF NOT EXISTS retaildb;"
       - name: Increase Connection Limit
         run: |
